### ISSUE TITLE
Mac OS crashing on initialization

### ISSUE THREAD

**Issue by chenjing1294** [ikvmnet/ikvm#271] opened 2023-01-17 02:10 UTC
ikvm 8.4.4 , macOS-x64.

I have no problem running on Windows and Linux, but running on macOS-x64 has the following error log:
```
System.TypeInitializationException: The type initializer for 'javax.management.remote.JMXServiceURL' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'java.util.logging.Logger' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'java.util.logging.Level' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'IntegerCache' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'sun.misc.VM' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'java.lang.Props' threw an exception.
 ---> java.lang.NullPointerException
   --- End of inner exception stack trace ---
   at java.lang.System.get_lineSeparator()
   at sun.misc.VM..cctor()
   --- End of inner exception stack trace ---
   at sun.misc.VM.getSavedProperty(String key)
   at java.lang.Integer.IntegerCache..cctor()
   --- End of inner exception stack trace ---
   at java.lang.Integer.valueOf(Int32 i)
   at java.util.logging.Level.KnownLevel.add(Level l)
   at java.util.logging.Level..ctor(String name, Int32 value, String resourceBundleName, Boolean visible)
   at java.util.logging.Level..ctor(String name, Int32 value, String resourceBundleName)
   at java.util.logging.Level..cctor()
   --- End of inner exception stack trace ---
   at java.util.logging.Logger..cctor()
   --- End of inner exception stack trace ---
   at java.util.logging.Logger.getLogger(String name, CallerID)
   at com.sun.jmx.remote.util.ClassLogger..ctor(String subsystem, String className)
   at javax.management.remote.JMXServiceURL..cctor()
   --- End of inner exception stack trace ---
   at javax.management.remote.JMXServiceURL.__<clinit>()
   at com.redisant.jkafka.JmxApi..ctor(String hostname, Int32 port, String username, String password)
   at KafkaAssistant.ViewModels.Kafka.BrokerMetadataModel.Circle(Object source, ElapsedEventArgs e)
```

**Comment by chenjing1294** [comment] 2023-01-17 02:16
I am now publishing the macOS-x64 version on Windows, because the following error occurs when publishing on macOS-x64:
```
dotnet publish -c Release --runtime osx-x64 -p:PublishReadyToRun=true --self-contained true

.....
/Users/cj/.nuget/packages/ikvm.msbuild/8.4.4/buildTransitive/netstandard2.0/IKVM.MSBuild.Tasks.targets(25,9): error MSB4044: Task "IkvmGetReferenceAssemb" was not given a required parameter " ToolPath" assignment.
```

**Comment by wasabii** [comment] 2023-01-17 03:30
So, I don't have test machines to do OSX stuff. So there really isn't much I can do about this right now. We need somebody with Apple hardware to test.

**Comment by BiologyTools** [comment] 2023-01-27 07:43
I'm running into a similar error on Mac. The latest IKVM 8.4.4 got the library I'm using to work on Linux but on Mac I'm getting this error. I'm using VM to run on Mac maybe someone can do that to fix this issue.
`Unhandled exception. System.TypeInitializationException: The type initializer for 'loci.common.services.ServiceFactory' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'org.slf4j.LoggerFactory' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'java.lang.Props' threw an exception.
 ---> java.lang.NullPointerException
   --- End of inner exception stack trace ---
   at java.lang.System.get_props()
   at java.lang.System.getProperty(String key)
   at org.slf4j.helpers.Util.safeGetSystemProperty(String key)
   at org.slf4j.helpers.Util.safeGetBooleanSystemProperty(String key)
   at org.slf4j.LoggerFactory..cctor()
   --- End of inner exception stack trace ---
   at org.slf4j.LoggerFactory.getLogger(Class clazz)
   at loci.common.services.ServiceFactory..cctor()
   --- End of inner exception stack trace ---
   at loci.common.services.ServiceFactory..ctor()
   at BioGTK.BioImage.InitOME() in F:\Shared\Bio\BioGTK\BioGTK\Bio.cs:line 3112
   at System.Threading.Thread.StartCallback()
`

**Comment by wasabii** [comment] 2023-01-27 08:37
Same issue.

I can't do anything about it, not having a Mac.

**Comment by BiologyTools** [comment] 2023-01-27 08:57
@wasabii I would help but running Mac on VM is slow and I know C# but not Java. When will the next release or prerelease of IKVM be out? Hoping this issue might just fix itself.

**Comment by NightOwl888** [comment] 2023-01-27 10:23
> Same issue.
> 
> I can't do anything about it, not having a Mac.

FYI - you can rent a Mac for debugging purposes:

- https://www.macincloud.com/
- https://www.macstadium.com/
- https://www.youtube.com/watch?v=-lvEK0A142c

MacInCloud appears to be the cheapest paid option for debugging. If you don't rent for an extended period of time, it may be possible to create a setup script to quickly deploy a debugging configuration and do it in short spurts when it is deemed necessary.

MacStadium also advertises "free macOS for open source". Not sure whether it will work for IKVM, but is worth looking into.

- https://www.macstadium.com/opensource
- https://www.macobserver.com/news/macstadium-offers-free-hosting-for-open-source-developers/

Of course, if there are a few theories about what is happening, it may also be possible to use Azure DevOps or GitHub Actions with some extra logging during unit tests to confirm/rule out theories.

**Comment by dkocher** [comment] 2023-01-27 12:09
@wasabii I can provide access to x86-64/arm64 macOS for development/testing if you are interested.

**Comment by wasabii** [comment] 2023-01-27 14:24
I am. What are you proposing?

**Comment by dkocher** [comment] 2023-01-27 15:27
> I am. What are you proposing?

I could provide a SSH/VNC access to the hosts. They are running macOS 12.x with Xcode 13.4.x. Ping me by email to set this up.

**Comment by NightOwl888** [comment] 2023-02-05 15:21
I am getting a similar initialization issue on macOS on [the ikvm-initialization-exception-1 branch](https://github.com/NightOwl888/IkvmPublishDemo/tree/ikvm-initialization-exception-1). [This simple test](https://github.com/NightOwl888/IkvmPublishDemo/blob/ikvm-initialization-exception-1/tests/ICU4N.Tests/TestFoo.cs#L41-L49) is causing the issue.

However, the build is currently failing due to https://github.com/ikvm-revived/ikvm-maven/issues/29. After that is fixed, this issue can be investigated if you now have access to macOS for debugging. The build succeeded once and I got to the tests so was able to see this failure, but I have since deleted and recreated the pipeline to make it point to GitHub instead of Azure Repos.

**Comment by wasabii** [comment] 2023-07-29 02:57
A lot of changes have happened since this bug was opened. I have managed to run IKVM on OS X, for instance. Though there are things missing, at least the bug expressed in the topic didn't exist anymore. That said, we still don't have a test suite running on OS X, and I personally don't have the resources to test each release on OS X, so the problem is possible to start reaccurring.

I am working on solving the former problem.

But, for now, I'm going to go ahead and close this since I think it's probably fixed. If not, please reopen.

**Closed by wasabii** 2023-07-29 02:57 UTC

**Comment by BiologyTools** [comment] 2023-08-06 19:55
Turns out this is not an issue for the bioformats library either now it works on mac for me as well!
